import { createProjects, createProjectTemplates } from "@/lib/projects";
import { createIdeas } from "@/lib/evolve";
import { createCultureIdeas, createMonday, createOffboard, createPulses, createTraining } from "@/lib/life";
import { createGeorgeInbox } from "@/lib/command";
import { createCulture, createCultureSuggestions } from "@/lib/culture";
import { createGrowthNotes, createGrowthPlans, createGrowthReviews, createSkills } from "@/lib/growth";
import { createFeedback } from "@/lib/feedback";
import { createCheckins } from "@/lib/checkins";
import { createRollout } from "@/lib/rollout";
import { defaultModelRoutes } from "@/lib/models";
import { createReviews } from "@/lib/reviews";
import type {
  Connector,
  Decision,
  Department,
  FinishStep,
  InboxItem,
  Meeting,
  Membership,
  Model,
  Notice,
  OnboardingStep,
  Person,
  Task,
  Ticket,
} from "@/lib/types";

export const PEOPLE: Person[] = [
  {
    id: "nadia",
    name: "Nadia Reyes",
    firstName: "Nadia",
    initials: "NR",
    role: "employee",
    title: "Insurance specialist",
    departmentId: "insurance",
    email: "nadia.reyes@dpcp.example",
    tz: "AZ",
    goal: 85,
    execution: 88,
    streak: 6,
    savedToday: "2 h 15 m",
    shift: "8:00 AM – 4:30 PM AZ",
    backup1: "faisal",
    backup2: "sana",
    todayDone: 3,
    todayTotal: 9,
    status: "on_track",
    statusLabel: "On track",
    workingNow: "Reply to Mesa Ridge Dental re: collections",
  },
  {
    id: "omar",
    name: "Omar Hale",
    firstName: "Omar",
    initials: "OH",
    role: "leader",
    title: "Insurance lead",
    departmentId: "insurance",
    email: "omar.hale@dpcp.example",
    tz: "AZ",
    goal: 85,
    execution: 91,
    streak: 4,
    savedToday: "1 h 40 m",
    shift: "8:00 AM – 5:00 PM AZ",
    backup1: "nadia",
    backup2: "faisal",
    todayDone: 2,
    todayTotal: 5,
    status: "on_track",
    statusLabel: "On track",
    workingNow: "Unblock the Canyon View appeal",
    loadNote: "1 h free today",
  },
  {
    id: "george",
    name: "George",
    firstName: "George",
    initials: "GH",
    role: "george",
    title: "Owner",
    departmentId: "owner",
    email: "georgehariri@gmail.com",
    tz: "AZ",
    goal: 85,
    execution: 90,
    streak: 9,
    savedToday: "4 h 05 m",
    shift: "7:30 AM – 5:00 PM AZ",
    todayDone: 1,
    todayTotal: 4,
    status: "on_track",
    statusLabel: "On track",
    workingNow: "Approve the BrightDent deposit",
  },
  {
    id: "imran",
    name: "Imran Cole",
    firstName: "Imran",
    initials: "IC",
    role: "employee",
    title: "Appeals specialist",
    departmentId: "insurance",
    email: "imran.cole@dpcp.example",
    tz: "PKT",
    goal: 85,
    execution: 79,
    streak: 1,
    savedToday: "40 m",
    shift: "9:00 AM – 6:00 PM PKT",
    backup1: "faisal",
    backup2: "nadia",
    todayDone: 3,
    todayTotal: 10,
    status: "blocked",
    statusLabel: "Blocked 1 h 20 m",
    workingNow: "Appeal draft · Canyon View Smiles (batch 14)",
    loadNote: "Fully booked",
  },
  {
    id: "sana",
    name: "Sana Brooks",
    firstName: "Sana",
    initials: "SB",
    role: "employee",
    title: "Eligibility specialist",
    departmentId: "insurance",
    email: "sana.brooks@dpcp.example",
    tz: "PKT",
    goal: 85,
    execution: 81,
    streak: 2,
    savedToday: "1 h 05 m",
    shift: "9:00 AM – 6:00 PM PKT",
    backup1: "nadia",
    backup2: "imran",
    todayDone: 6,
    todayTotal: 11,
    status: "behind",
    statusLabel: "Behind ~1 h",
    workingNow: "Eligibility checks · Saguaro Family Dental",
    loadNote: "30 m free today",
  },
  {
    id: "faisal",
    name: "Faisal Adeyemi",
    firstName: "Faisal",
    initials: "FA",
    role: "employee",
    title: "Payment posting",
    departmentId: "insurance",
    email: "faisal.adeyemi@dpcp.example",
    tz: "PKT",
    goal: 85,
    execution: 92,
    streak: 8,
    savedToday: "2 h",
    shift: "9:00 AM – 6:00 PM PKT",
    backup1: "nadia",
    backup2: "sana",
    todayDone: 8,
    todayTotal: 10,
    status: "on_track",
    statusLabel: "On track",
    workingNow: "Payment posting · Desert Bloom Dental",
    loadNote: "2 h free today",
  },
  {
    id: "hina",
    name: "Hina Moss",
    firstName: "Hina",
    initials: "HM",
    role: "employee",
    title: "AR follow-up",
    departmentId: "insurance",
    email: "hina.moss@dpcp.example",
    tz: "PKT",
    goal: 85,
    execution: 86,
    streak: 3,
    savedToday: "0 m",
    shift: "9:00 AM – 6:00 PM PKT",
    backup1: "faisal",
    backup2: "sana",
    todayDone: 0,
    todayTotal: 0,
    status: "time_off",
    statusLabel: "Time off",
    workingNow: "Out today · 2 urgent items covered by Faisal",
    timeOff: true,
  },
  {
    id: "leila",
    name: "Leila Okonkwo",
    firstName: "Leila",
    initials: "LO",
    role: "leader",
    title: "Coaching lead",
    departmentId: "coaching",
    email: "leila.okonkwo@dpcp.example",
    tz: "AZ",
    goal: 85,
    execution: 93,
    streak: 5,
    savedToday: "1 h",
    shift: "8:00 AM – 4:00 PM AZ",
    todayDone: 4,
    todayTotal: 6,
    status: "on_track",
    statusLabel: "On track",
    workingNow: "QA the Sunridge action plan",
  },
  {
    id: "rowan",
    name: "Rowan Blake",
    firstName: "Rowan",
    initials: "RB",
    role: "leader",
    title: "Operations lead",
    departmentId: "operations",
    email: "rowan.blake@dpcp.example",
    tz: "SAST",
    goal: 85,
    execution: 83,
    streak: 2,
    savedToday: "50 m",
    shift: "8:00 AM – 5:00 PM SAST",
    todayDone: 5,
    todayTotal: 8,
    status: "on_track",
    statusLabel: "On track",
    workingNow: "Friday pillar report",
  },
  {
    id: "amina",
    name: "Amina Farouk",
    firstName: "Amina",
    initials: "AF",
    role: "administrator",
    canManageTeams: true,
    title: "People & Staffing lead",
    departmentId: "staffing",
    email: "amina.farouk@dpcp.example",
    tz: "AZ",
    goal: 85,
    execution: 88,
    streak: 3,
    savedToday: "1 h 10 m",
    shift: "8:00 AM – 5:00 PM AZ",
    todayDone: 3,
    todayTotal: 7,
    status: "on_track",
    statusLabel: "On track",
    workingNow: "Assign Jamie's first-week path",
  },
  {
    id: "priya",
    name: "Priya Shah",
    firstName: "Priya",
    initials: "PS",
    role: "leader",
    title: "Marketing lead",
    departmentId: "marketing",
    email: "priya.shah@dpcp.example",
    tz: "AZ",
    goal: 85,
    execution: 76,
    streak: 0,
    savedToday: "35 m",
    shift: "9:00 AM – 5:30 PM AZ",
    todayDone: 2,
    todayTotal: 8,
    status: "behind",
    statusLabel: "Behind ~2 h",
    workingNow: "Weekly snapshot · Hill Ridge Dental",
  },
  {
    id: "elena",
    name: "Elena Voss",
    firstName: "Elena",
    initials: "EV",
    role: "leader",
    title: "Finance lead",
    departmentId: "finance",
    email: "elena.voss@dpcp.example",
    tz: "AZ",
    goal: 85,
    execution: 94,
    streak: 7,
    savedToday: "2 h",
    shift: "8:00 AM – 4:30 PM AZ",
    todayDone: 4,
    todayTotal: 5,
    status: "on_track",
    statusLabel: "On track",
    workingNow: "Payroll exceptions",
  },
  {
    id: "jonas",
    name: "Jonas Keller",
    firstName: "Jonas",
    initials: "JK",
    role: "leader",
    title: "Supplies lead",
    departmentId: "supplies",
    email: "jonas.keller@dpcp.example",
    tz: "PKT",
    goal: 85,
    execution: 80,
    streak: 2,
    savedToday: "1 h",
    shift: "9:00 AM – 6:00 PM PKT",
    todayDone: 3,
    todayTotal: 7,
    status: "on_track",
    statusLabel: "On track",
    workingNow: "FDA blanks on container 4",
  },
  {
    id: "theo",
    name: "Theo March",
    firstName: "Theo",
    initials: "TM",
    role: "leader",
    title: "Equipment lead",
    departmentId: "equipment",
    email: "theo.march@dpcp.example",
    tz: "SAST",
    goal: 85,
    execution: 71,
    streak: 1,
    savedToday: "20 m",
    shift: "8:00 AM – 5:00 PM SAST",
    todayDone: 1,
    todayTotal: 6,
    status: "behind",
    statusLabel: "Behind ~3 h",
    workingNow: "Lease differences · Mesa Verde Plaza",
  },
  {
    id: "jamie",
    name: "Jamie Okonkwo",
    firstName: "Jamie",
    initials: "JO",
    role: "employee",
    title: "New hire · insurance",
    departmentId: "insurance",
    email: "jamie.okonkwo@dpcp.example",
    tz: "AZ",
    goal: 85,
    execution: 0,
    streak: 0,
    savedToday: "0 m",
    shift: "8:00 AM – 4:30 PM AZ",
    backup1: "faisal",
    backup2: "nadia",
    todayDone: 2,
    todayTotal: 7,
    status: "not_started",
    statusLabel: "Not started",
    workingNow: "Day 1 setup",
  },
];

export const DEPARTMENTS: Department[] = [
  { id: "insurance", name: "Insurance & Billing", family: "insurance", leadId: "omar", onTime: 84, overdue: 2, blocked: 1, todayDone: 41, todayTotal: 63 },
  { id: "coaching", name: "Coaching", family: "dpcp", leadId: "leila", onTime: 91, overdue: 0, blocked: 0, todayDone: 18, todayTotal: 22 },
  { id: "operations", name: "Operations", family: "dpcp", leadId: "rowan", onTime: 83, overdue: 1, blocked: 0, todayDone: 14, todayTotal: 20 },
  { id: "staffing", name: "People & Staffing", family: "staffing", leadId: "amina", onTime: 88, overdue: 1, blocked: 0, todayDone: 9, todayTotal: 14 },
  { id: "marketing", name: "Marketing", family: "marketing", leadId: "priya", onTime: 76, overdue: 3, blocked: 1, todayDone: 6, todayTotal: 15 },
  { id: "finance", name: "Finance", family: "finance", leadId: "elena", onTime: 94, overdue: 0, blocked: 0, todayDone: 11, todayTotal: 13 },
  { id: "supplies", name: "Supplies", family: "supplies", leadId: "jonas", onTime: 80, overdue: 1, blocked: 1, todayDone: 8, todayTotal: 16 },
  { id: "equipment", name: "Equipment", family: "equipment", leadId: "theo", onTime: 71, overdue: 2, blocked: 1, todayDone: 4, todayTotal: 12 },
];

const mesaDraft = `Hi Laura, good question. Two payer batches ($14,210 total) were posted on Oct 2, so they'll show in October. Adjusted for timing, September is in line with August. I've attached the batch list. Happy to walk through it on a quick call.

Nadia`;

function baseTask(partial: Omit<Task, "steps" | "history" | "comments" | "related" | "skips"> & Partial<Task>): Task {
  return {
    steps: partial.steps ?? [],
    history: partial.history ?? [],
    comments: partial.comments ?? [],
    related: partial.related ?? [],
    skips: partial.skips ?? 0,
    ...partial,
  };
}

export function createTasks(): Task[] {
  return [
    baseTask({
      id: "nadia-done-1",
      ownerId: "nadia",
      departmentId: "insurance",
      title: "File the August receipt batch",
      why: "Receipts were matched and filed.",
      kind: "human",
      status: "done",
      sourceLabel: "From app",
      sourceKind: "app",
      dueLabel: "Done",
      dueTone: "green",
      originalDue: "Oct 20, 9:00 AM",
      currentDue: "Oct 20, 9:00 AM",
      estimateMin: 15,
      spentMin: 12,
      prepared: ["Matched 18 receipts"],
      doneDefinition: "Filed",
      order: 1,
      doneAt: "9:10 AM AZ",
    }),
    baseTask({
      id: "nadia-done-2",
      ownerId: "nadia",
      departmentId: "insurance",
      title: "Confirm Friday stand-up notes",
      why: "Notes were already in the thread.",
      kind: "human",
      status: "done",
      sourceLabel: "From Slack · #insurance",
      sourceKind: "slack",
      dueLabel: "Done",
      dueTone: "green",
      originalDue: "Oct 20, 9:30 AM",
      currentDue: "Oct 20, 9:30 AM",
      estimateMin: 10,
      spentMin: 8,
      prepared: [],
      doneDefinition: "Confirmed",
      order: 2,
      doneAt: "9:28 AM AZ",
    }),
    baseTask({
      id: "nadia-done-3",
      ownerId: "nadia",
      departmentId: "insurance",
      title: "Enter the Desert Bloom morning count",
      why: "Count only. No patient detail.",
      kind: "human",
      status: "done",
      sourceLabel: "Standing schedule",
      sourceKind: "app",
      dueLabel: "Done",
      dueTone: "green",
      originalDue: "Oct 20, 10:00 AM",
      currentDue: "Oct 20, 10:00 AM",
      estimateMin: 20,
      spentMin: 18,
      prepared: [],
      doneDefinition: "Count entered",
      order: 3,
      doneAt: "10:02 AM AZ",
      proof: "46 done, 0 exceptions",
    }),
    baseTask({
      id: "nadia-mesa",
      ownerId: "nadia",
      departmentId: "insurance",
      title: "Reply to Mesa Ridge Dental about their September collections report",
      why: "Office manager asked why collections dropped 8% vs August. I checked the report: two large payer batches posted Oct 2 instead of Sept 30. Draft reply is ready.",
      kind: "approval",
      status: "open",
      sourceLabel: "From email · Mesa Ridge Dental",
      sourceKind: "email",
      dueLabel: "Due 12:00 PM",
      dueTone: "amber",
      originalDue: "Oct 20, 12:00 PM",
      currentDue: "Oct 20, 12:00 PM",
      estimateMin: 10,
      spentMin: 4,
      recipient: "Laura",
      client: "Mesa Ridge Dental",
      draft: {
        channel: "gmail",
        accountLabel: "Draft reply (sends from your Gmail, same thread)",
        body: mesaDraft,
      },
      prepared: [
        "Compared Sept vs Aug collections",
        "Found the 2 late batches (attached)",
        "Checked: no open denials explain the gap",
        "SOP: “Client report questions” step 3",
      ],
      doneDefinition: "Done = reply sent in thread",
      sop: { name: "Client report questions", section: "step 3" },
      steps: [
        { id: "s1", label: "Compare the two months", state: "done" },
        { id: "s2", label: "Check denials and timing", state: "done" },
        { id: "s3", label: "Send the reply from your account", state: "current" },
      ],
      history: [
        { id: "h1", at: "9:58 AM AZ", actor: "AI", text: "Compared September and August collections." },
        { id: "h2", at: "10:05 AM AZ", actor: "AI", text: "Drafted the reply and attached the batch list." },
      ],
      related: [{ label: "Mesa Ridge client record", href: "/messages" }],
      order: 4,
    }),
    baseTask({
      id: "nadia-prep",
      ownerId: "nadia",
      departmentId: "insurance",
      title: "Prep for 1:00 PM call with Canyon View Smiles",
      why: "Agenda, last open items, and the AR aging buckets are ready. Counts and status only.",
      kind: "meeting",
      status: "open",
      sourceLabel: "From calendar",
      sourceKind: "meeting",
      dueLabel: "Due 12:45 PM",
      dueTone: "neutral",
      originalDue: "Oct 20, 12:45 PM",
      currentDue: "Oct 20, 12:45 PM",
      estimateMin: 40,
      spentMin: 0,
      client: "Canyon View Smiles",
      prepared: ["Agenda", "Three open items from Sept 22", "AR aging buckets (no patient detail)"],
      doneDefinition: "Prep read before the call",
      sop: { name: "Client call prep", section: "section 1" },
      steps: [
        { id: "p1", label: "Read the one-page prep", state: "current" },
        { id: "p2", label: "Join the meeting", state: "todo" },
      ],
      history: [{ id: "ph", at: "7:40 AM AZ", actor: "AI", text: "Built the prep from the last recap and open promises." }],
      related: [{ label: "Open the meeting", href: "/meetings/canyon" }],
      order: 5,
    }),
    baseTask({
      id: "nadia-verify",
      ownerId: "nadia",
      departmentId: "insurance",
      title: "Log Desert Bloom verification exceptions",
      why: "46 checks were planned for Tue–Wed. Enter the count and how many need a call. Work happens in the practice system, not here.",
      kind: "human",
      status: "open",
      sourceLabel: "Standing schedule",
      sourceKind: "app",
      dueLabel: "Due 2:00 PM",
      dueTone: "neutral",
      originalDue: "Oct 20, 2:00 PM",
      currentDue: "Oct 20, 2:00 PM",
      estimateMin: 90,
      spentMin: 20,
      client: "Desert Bloom Dental",
      prepared: ["Queue size: 46", "SOP: Eligibility v4"],
      doneDefinition: "Count + exception total entered",
      proofRequired: true,
      sop: { name: "Eligibility v4", section: "close-out" },
      steps: [
        { id: "v1", label: "Work the queue in the practice system", state: "current" },
        { id: "v2", label: "Enter count and exceptions here", state: "todo" },
      ],
      history: [],
      order: 6,
    }),
    baseTask({
      id: "nadia-wait",
      ownerId: "nadia",
      departmentId: "insurance",
      title: "Deposit info from Saguaro Family Dental",
      why: "Waiting on Laura since 1:00 PM. I'll nudge her at 3:00.",
      kind: "human",
      status: "waiting",
      sourceLabel: "From email · Saguaro Family Dental",
      sourceKind: "email",
      dueLabel: "Waiting",
      dueTone: "amber",
      originalDue: "Oct 20, 3:00 PM",
      currentDue: "Oct 20, 3:00 PM",
      estimateMin: 15,
      spentMin: 5,
      recipient: "Laura",
      client: "Saguaro Family Dental",
      waitingNote: "Waiting on Laura since 1:00 PM. I'll nudge her at 3:00.",
      prepared: ["Asked for the deposit date only. No patient detail."],
      doneDefinition: "Deposit date logged",
      steps: [{ id: "w1", label: "Log the date when it arrives", state: "current" }],
      history: [{ id: "wh", at: "1:05 PM AZ", actor: "AI", text: "Sent a reminder draft. You approved it." }],
      order: 7,
    }),
    baseTask({
      id: "nadia-appeals",
      ownerId: "nadia",
      departmentId: "insurance",
      title: "Appeal deadline check · Canyon View Smiles",
      why: "4 appeals are due this week. DPCP OS tracks the count and the deadline. The letters stay in the practice system.",
      kind: "human",
      status: "open",
      sourceLabel: "Deadline tracker",
      sourceKind: "app",
      dueLabel: "Due 3:30 PM",
      dueTone: "neutral",
      originalDue: "Oct 24, 5:00 PM",
      currentDue: "Oct 20, 3:30 PM",
      estimateMin: 45,
      spentMin: 0,
      client: "Canyon View Smiles",
      prepared: ["4 open", "Earliest deadline Oct 24"],
      doneDefinition: "Each appeal has a status and a date",
      steps: [{ id: "a1", label: "Confirm the four statuses", state: "current" }],
      history: [],
      order: 8,
    }),
    baseTask({
      id: "nadia-backup",
      ownerId: "nadia",
      departmentId: "insurance",
      title: "Confirm Thursday coverage with Faisal",
      why: "Your time off starts Thursday. Faisal is the first backup. Sana is second.",
      kind: "human",
      status: "open",
      sourceLabel: "Time off plan",
      sourceKind: "app",
      dueLabel: "Due 4:00 PM",
      dueTone: "neutral",
      originalDue: "Oct 20, 4:00 PM",
      currentDue: "Oct 20, 4:00 PM",
      estimateMin: 20,
      spentMin: 0,
      prepared: ["Urgent items route to Faisal", "Holding replies wait for his approval"],
      doneDefinition: "Faisal has the coverage note",
      steps: [],
      history: [],
      order: 9,
    }),
    baseTask({
      id: "imran-appeal",
      ownerId: "imran",
      departmentId: "insurance",
      title: "Appeal draft · Canyon View Smiles (batch 14)",
      why: "Waiting on the practice for the EOB copy since 1:00 PM. A reminder draft was approved at 1:05 PM. No reply yet.",
      kind: "human",
      status: "blocked",
      sourceLabel: "From email · Canyon View Smiles",
      sourceKind: "email",
      dueLabel: "Blocked",
      dueTone: "red",
      originalDue: "Oct 27, 5:00 PM",
      currentDue: "Oct 20, 4:00 PM",
      estimateMin: 40,
      spentMin: 70,
      client: "Canyon View Smiles",
      blockedReason: "Waiting on a client",
      prepared: ["Deadline is Oct 27, so tomorrow is still safe", "Suggestion: call the front desk or move the appeal to tomorrow"],
      doneDefinition: "Appeal status updated",
      steps: [
        { id: "i1", label: "Get the EOB copy from the practice", state: "current" },
        { id: "i2", label: "Update the appeal status", state: "todo" },
      ],
      history: [
        { id: "ih1", at: "1:00 PM AZ", actor: "Imran Cole", text: "Marked blocked. Waiting on the practice." },
        { id: "ih2", at: "1:05 PM AZ", actor: "AI", text: "Reminder draft approved and sent." },
      ],
      order: 4,
    }),
    baseTask({
      id: "omar-done-1",
      ownerId: "omar",
      departmentId: "insurance",
      title: "Read the morning team brief",
      why: "Brief was ready at 7:30.",
      kind: "review",
      status: "done",
      sourceLabel: "From app",
      sourceKind: "app",
      dueLabel: "Done",
      dueTone: "green",
      originalDue: "Oct 20, 8:00 AM",
      currentDue: "Oct 20, 8:00 AM",
      estimateMin: 10,
      spentMin: 8,
      prepared: [],
      doneDefinition: "Read",
      order: 1,
      doneAt: "8:05 AM AZ",
    }),
    baseTask({
      id: "omar-done-2",
      ownerId: "omar",
      departmentId: "insurance",
      title: "Approve Sana's internal check-in",
      why: "Internal note only.",
      kind: "approval",
      status: "done",
      sourceLabel: "From Slack",
      sourceKind: "slack",
      dueLabel: "Done",
      dueTone: "green",
      originalDue: "Oct 20, 9:00 AM",
      currentDue: "Oct 20, 9:00 AM",
      estimateMin: 5,
      spentMin: 4,
      prepared: [],
      doneDefinition: "Sent",
      order: 2,
      doneAt: "9:04 AM AZ",
    }),
    baseTask({
      id: "omar-unblock",
      ownerId: "omar",
      departmentId: "insurance",
      title: "Imran is blocked on the Canyon View appeal",
      why: "Waiting on the practice for the EOB copy since 1:00 PM. A reminder went out at 1:05 PM and there is no reply. Suggestion: call the front desk or move the appeal to tomorrow (deadline is Oct 27, so no risk).",
      kind: "decision",
      status: "open",
      sourceLabel: "From Imran's task",
      sourceKind: "app",
      dueLabel: "Needs you",
      dueTone: "red",
      originalDue: "Oct 27, 5:00 PM",
      currentDue: "Oct 20, 11:00 AM",
      estimateMin: 10,
      spentMin: 0,
      client: "Canyon View Smiles",
      prepared: [
        "Blocked 1 h 20 m",
        "Time on task is over the estimate",
        "Deadline Oct 27",
      ],
      doneDefinition: "Imran is unblocked or the date has moved",
      options: ["Move to tomorrow", "Reassign", "Message Imran"],
      steps: [],
      history: [{ id: "oh", at: "1:06 PM AZ", actor: "AI", text: "Flagged the block for you." }],
      related: [{ label: "Imran's task", href: "/tasks/imran-appeal" }],
      order: 3,
    }),
    baseTask({
      id: "omar-saguaro",
      ownerId: "omar",
      departmentId: "insurance",
      title: "Ask Saguaro for the missing deposit date",
      why: "The practice has not sent the deposit date. The draft asks for the date only.",
      kind: "approval",
      status: "open",
      sourceLabel: "From email · Saguaro Family Dental",
      sourceKind: "email",
      dueLabel: "Due 1:30 PM",
      dueTone: "amber",
      originalDue: "Oct 20, 1:30 PM",
      currentDue: "Oct 20, 1:30 PM",
      estimateMin: 10,
      spentMin: 0,
      recipient: "the office manager",
      client: "Saguaro Family Dental",
      draft: {
        channel: "gmail",
        accountLabel: "Draft reply (sends from your Gmail, same thread)",
        body: "Hi, we still need the deposit date for last week's batch so we can close the status. No other detail is needed. Thank you.",
      },
      prepared: ["Counts only. No patient information in the draft."],
      doneDefinition: "Reply sent",
      steps: [],
      history: [],
      order: 4,
    }),
    baseTask({
      id: "george-done-1",
      ownerId: "george",
      departmentId: "owner",
      title: "Read the morning company brief",
      why: "On-time is 84% against an 80% target. Two decisions are waiting.",
      kind: "review",
      status: "done",
      sourceLabel: "From app",
      sourceKind: "app",
      dueLabel: "Done",
      dueTone: "green",
      originalDue: "Oct 20, 8:00 AM",
      currentDue: "Oct 20, 8:00 AM",
      estimateMin: 10,
      spentMin: 9,
      prepared: [],
      doneDefinition: "Read",
      order: 1,
      doneAt: "7:50 AM AZ",
    }),
    baseTask({
      id: "george-deposit",
      ownerId: "george",
      departmentId: "owner",
      title: "Approve $2,400 deposit to BrightDent Supply",
      why: "Supplies checked the proforma. Three SKUs are still missing FDA data, so this deposit covers only the cleared lines.",
      kind: "decision",
      status: "open",
      sourceLabel: "From Jonas Keller",
      sourceKind: "app",
      dueLabel: "Due today",
      dueTone: "amber",
      originalDue: "Oct 20, 3:00 PM",
      currentDue: "Oct 20, 3:00 PM",
      estimateMin: 10,
      spentMin: 0,
      prepared: ["Payee is on the approved list", "Amount is above $500, so it needs you", "No payment is released by AI"],
      doneDefinition: "Approved or declined, with the amount and payee recorded",
      options: ["Approve", "Decline", "Ask a question"],
      money: { amount: "$2,400", payee: "BrightDent Supply" },
      steps: [],
      history: [{ id: "gh", at: "8:10 AM AZ", actor: "Jonas Keller", text: "Asked you to approve the deposit." }],
      order: 2,
    }),
    baseTask({
      id: "george-sku",
      ownerId: "george",
      departmentId: "owner",
      title: "Remove uncleared SKU X5, or hold the shipment?",
      why: "Three SKUs are missing FDA data. Booking stays blocked until you choose.",
      kind: "decision",
      status: "open",
      sourceLabel: "From supplies",
      sourceKind: "app",
      dueLabel: "Due today",
      dueTone: "red",
      originalDue: "Oct 20, 4:00 PM",
      currentDue: "Oct 20, 4:00 PM",
      estimateMin: 15,
      spentMin: 0,
      prepared: ["Booking is already blocked"],
      doneDefinition: "A choice is recorded",
      options: ["Remove the SKU", "Hold the shipment"],
      steps: [],
      history: [],
      order: 3,
    }),
    baseTask({
      id: "george-offer",
      ownerId: "george",
      departmentId: "owner",
      title: "Sign the offer letter for a hygienist",
      why: "People & Staffing filled the template for a fictional clinic role. You are the signer.",
      kind: "decision",
      status: "open",
      sourceLabel: "From Amina Farouk",
      sourceKind: "app",
      dueLabel: "Due Wednesday",
      dueTone: "neutral",
      originalDue: "Oct 22, 12:00 PM",
      currentDue: "Oct 22, 12:00 PM",
      estimateMin: 15,
      spentMin: 0,
      prepared: ["Template fields checked", "No pay figure is shown in this prototype"],
      doneDefinition: "Signed or sent back",
      options: ["Approve", "Send back"],
      steps: [],
      history: [],
      order: 4,
    }),
  ];
}

export function createMessages(): InboxItem[] {
  return [
    {
      id: "msg-mesa",
      ownerId: "nadia",
      tab: "reply",
      source: "Gmail",
      sourceKind: "gmail",
      from: "Laura Chen",
      org: "Mesa Ridge Dental",
      subject: "September collections",
      summary: "Asked why collections dropped 8%. Draft ready.",
      time: "8:14 AM AZ",
      body: "Hi Nadia, our September collections look about 8% under August. Can you tell me what changed? Laura",
      draft: mesaDraft,
      triage: "Needs reply · client asked a question · confidence high · on your Today list as task 4",
      taskId: "nadia-mesa",
      unread: true,
      client: true,
      slaLabel: "1h 32m left",
      slaTone: "amber",
    },
    {
      id: "msg-patel",
      ownerId: "nadia",
      tab: "reply",
      source: "Gmail",
      sourceKind: "gmail",
      from: "Dr. Patel",
      org: "Saguaro Family Dental",
      subject: "Eligibility question",
      summary: "Needs you. A short reply is prepared.",
      time: "Mon 4:10 PM AZ",
      body: "Nadia, can you confirm whether the new associate is eligible to bill this week? Dr. Patel",
      draft: "Yes. The associate can bill starting Wednesday. I'll send the payer list with this note. Nadia",
      triage: "Needs you · email this week",
      client: true,
      slaLabel: "SLA missed · 18h",
      slaTone: "red",
    },
    {
      id: "msg-slack",
      ownerId: "nadia",
      tab: "reply",
      source: "Slack · #insurance",
      sourceKind: "slack",
      from: "Omar Hale",
      org: "Dental Practice Copilot",
      subject: "Can you take the 1:00 prep?",
      summary: "Asks you to own the Canyon View prep. Draft ready.",
      time: "9:02 AM AZ",
      body: "Nadia, can you own the 1:00 Canyon View prep? I added the aging buckets.",
      draft: "Yes, I'll have it read before 12:45. Nadia",
      triage: "Needs reply · internal · confidence high · on your Today list",
      taskId: "nadia-prep",
    },
    {
      id: "msg-decide",
      ownerId: "nadia",
      tab: "decision",
      source: "Gmail",
      sourceKind: "gmail",
      from: "Office manager",
      org: "Canyon View Smiles",
      subject: "Move Thursday's call?",
      summary: "They want Thursday instead of today. Pick an option.",
      time: "9:40 AM AZ",
      body: "Could we move today's 1:00 to Thursday at the same time?",
      triage: "Needs decision · scheduling · confidence high",
      options: ["Accept", "Counter", "Decline", "Ask Omar"],
      client: true,
      slaLabel: "2h 18m left",
      slaTone: "amber",
    },
    {
      id: "msg-handled",
      ownerId: "nadia",
      tab: "handled",
      source: "Slack · #insurance",
      sourceKind: "slack",
      from: "Faisal Adeyemi",
      org: "Dental Practice Copilot",
      subject: "Where is the posting SOP?",
      summary: "Answered from the SOP and linked the section.",
      time: "8:55 AM AZ",
      body: "Where do I start on a posting mismatch?",
      triage: "Handled by AI · internal SOP question · confidence high",
    },
    {
      id: "msg-filed",
      ownerId: "nadia",
      tab: "filed",
      source: "Gmail",
      sourceKind: "gmail",
      from: "News",
      org: "Payer bulletin",
      subject: "October bulletin",
      summary: "Newsletter. Filed. Nothing for you to do.",
      time: "7:12 AM AZ",
      body: "This month's bulletin is attached for your records.",
      triage: "Filed · newsletter",
    },
    {
      id: "msg-held",
      ownerId: "nadia",
      tab: "held",
      source: "Gmail",
      sourceKind: "gmail",
      from: "Front desk",
      org: "Desert Bloom Dental",
      subject: "Chart update",
      summary: "Held: may contain patient information. The AI didn't read this.",
      time: "10:18 AM AZ",
      body: "This message was held by the safety screen. The body is redacted in DPCP OS. Handle it in the practice system, or confirm it has no patient information before anyone releases it.",
      triage: "Held for review · pattern check · not sent to AI",
      client: true,
    },
  ];
}

export function createMeetings(): Meeting[] {
  return [
    {
      id: "canyon",
      title: "Canyon View Smiles",
      when: "1:00 PM",
      zone: "AZ",
      dayGroup: "Today",
      type: "Client",
      category: "client",
      prep: "Ready",
      notes: "Upcoming",
      attendees: ["Nadia Reyes", "Omar Hale", "Office manager"],
      leadId: "nadia",
      meetLabel: "Google Meet",
      agenda: ["AR aging buckets", "Missing deposit date", "Next month's verification window"],
      openItems: ["Deposit date still open (Saguaro is a different client)", "Batch 14 appeal is blocked"],
    },
    {
      id: "sunridge",
      title: "Sunridge Dental weekly",
      when: "Thu 10:00 AM",
      zone: "AZ",
      dayGroup: "Coming up",
      type: "Client",
      category: "client",
      prep: "Preparing",
      notes: "Upcoming",
      attendees: ["Leila Okonkwo", "George"],
      leadId: "leila",
      meetLabel: "Google Meet",
      agenda: ["Last action plan", "Open promises"],
      openItems: ["Prep usually ready an hour before"],
    },
    {
      id: "friday-report",
      title: "Friday report working session",
      when: "Fri 11:00 AM",
      zone: "AZ",
      dayGroup: "Coming up",
      type: "Internal",
      category: "internal",
      prep: "Not needed",
      notes: "Upcoming",
      attendees: ["Rowan Blake", "Jonas Keller"],
      leadId: "rowan",
      meetLabel: "Google Meet",
      agenda: ["Counts only", "What is late"],
      openItems: [],
    },
    {
      id: "standup",
      title: "Stand-up Meeting",
      when: "Yesterday 9:00 AM",
      zone: "AZ",
      dayGroup: "Past",
      type: "Internal",
      category: "daily",
      slot: "morning",
      departmentId: "insurance",
      kind: "daily",
      prep: "Not needed",
      notes: "Recap ready",
      attendees: ["Omar Hale", "Nadia Reyes", "Imran Cole", "Sana Brooks", "Faisal Adeyemi"],
      leadId: "omar",
      meetLabel: "Google Meet",
      agenda: [],
      openItems: [],
      recap: [
        "Saguaro deposit date is still missing.",
        "Canyon View appeal is waiting on the practice.",
        "Desert Bloom counts will be entered today.",
        "Hina is out. Faisal is covering two urgent items.",
      ],
      actions: [
        { id: "ma1", text: "Log Desert Bloom exceptions", owner: "Nadia Reyes", due: "Today", status: "Proposed" },
        { id: "ma2", text: "Call Canyon View front desk", owner: "Imran Cole", due: "Today", status: "Proposed" },
        { id: "ma3", text: "Cover Hina's urgent AR items", owner: "Faisal Adeyemi", due: "Today", status: "Confirmed" },
        { id: "ma4", text: "Decide who owns the new verification window", owner: "", due: "", status: "Needs owner" },
      ],
    },
    ...dailyMeetings(),
    ...teamMeetings(),
  ];
}

function teamMeetings(): Meeting[] {
  return DEPARTMENTS.map((dept) => {
    const georgeLed = dept.id === "coaching";
    return {
      id: `team-${dept.id}`,
      title: `${dept.name} Team Meeting`,
      when: georgeLed ? "Wed 2:00 PM" : "Wed 9:30 AM",
      zone: PEOPLE.find((p) => p.id === dept.leadId)?.tz ?? "AZ",
      dayGroup: "Coming up" as const,
      type: "Internal" as const,
      category: "team" as const,
      ledBy: georgeLed ? ("george" as const) : ("leader" as const),
      prep: "Not needed" as const,
      notes: "Upcoming" as const,
      attendees: PEOPLE.filter((p) => p.departmentId === dept.id && !p.timeOff).map((p) => p.name),
      leadId: georgeLed ? "george" : dept.leadId,
      meetLabel: "Google Meet",
      agenda: ["What the team is carrying", "What needs a decision", "What can wait"],
      openItems: [],
      departmentId: dept.id,
    };
  });
}

function dailyMeetings(): Meeting[] {
  return DEPARTMENTS.flatMap((dept) => {
    const zone = PEOPLE.find((p) => p.id === dept.leadId)?.tz ?? "AZ";
    const morning: Meeting = {
      id: `daily-${dept.id}-morning`,
      title: "Stand-up Meeting",
      when: "8:15 AM",
      zone,
      dayGroup: "Today",
      type: "Internal",
      category: "daily",
      prep: "Not needed",
      notes: "Recap ready",
      attendees: PEOPLE.filter((p) => p.departmentId === dept.id && !p.timeOff).map((p) => p.name),
      leadId: dept.leadId,
      meetLabel: "Google Meet",
      agenda: ["What did you finish yesterday?", "What are you taking today?", "What's blocking you?"],
      openItems: [],
      kind: "daily",
      slot: "morning",
      departmentId: dept.id,
      recap:
        dept.id === "insurance"
          ? [
              "Mesa Ridge reply is with Nadia.",
              "Canyon View appeal is blocked on a copy from the practice.",
              "Hina is out. Faisal is covering.",
            ]
          : ["Yesterday's leftovers were named.", "Today's commitments were named.", "Blockers were named."],
    };
    const evening: Meeting = {
      id: `daily-${dept.id}-evening`,
      title: "Update Meeting",
      when: "4:15 PM",
      zone,
      dayGroup: "Today",
      type: "Internal",
      category: "daily",
      prep: "Not needed",
      notes: "Upcoming",
      attendees: PEOPLE.filter((p) => p.departmentId === dept.id && !p.timeOff).map((p) => p.name),
      leadId: dept.leadId,
      meetLabel: "Google Meet",
      agenda: ["What got done today?", "What didn't get done?", "What are you handing off?"],
      openItems: ["If you miss this meeting, do the same three questions with AI."],
      kind: "daily",
      slot: "evening",
      departmentId: dept.id,
    };
    return [morning, evening];
  });
}

export function createDecisions(): Decision[] {
  return [
    {
      id: "dec-deposit",
      title: "Approve $2,400 deposit to BrightDent Supply",
      asker: "Jonas Keller",
      context: "Cleared SKUs only. Three SKUs with missing FDA data are excluded.",
      kind: "money",
      amount: "$2,400",
      payee: "BrightDent Supply",
      deadline: "Today 3:00 PM AZ",
      urgency: "today",
      options: ["Approve", "Decline", "Ask a question"],
      status: "open",
    },
    {
      id: "dec-sku",
      title: "Remove uncleared SKU X5, or hold the shipment?",
      asker: "Jonas Keller",
      context: "Booking is blocked until this is decided.",
      kind: "legal",
      deadline: "Today 4:00 PM AZ",
      urgency: "today",
      options: ["Remove the SKU", "Hold the shipment"],
      status: "open",
    },
    {
      id: "dec-offer",
      title: "Sign the hygienist offer",
      asker: "Amina Farouk",
      context: "Template is filled. Pay is not shown in this prototype.",
      kind: "hiring",
      deadline: "Wed Oct 22",
      urgency: "week",
      options: ["Approve", "Send back"],
      status: "open",
    },
    {
      id: "dec-policy",
      title: "Send the work-systems notice to the whole company?",
      asker: "Amina Farouk",
      context: "People & Staffing asked for your OK before a company-wide notice.",
      kind: "policy",
      deadline: "This week",
      urgency: "week",
      options: ["Approve", "Send back"],
      status: "open",
    },
    {
      id: "dec-price",
      title: "Price the Coastline Dental website quote",
      asker: "Priya Shah",
      context: "Scope is written. The price is yours.",
      kind: "escalation",
      deadline: "Fri Oct 23",
      urgency: "later",
      options: ["Approve", "Ask a question"],
      status: "open",
    },
  ];
}

export const NOTICE: Notice = {
  id: "notice-phi",
  title: "New rule: no client health information in Slack or chat",
  from: "George",
  when: "Oct 20, 8:05 AM",
  body: "Starting today, never paste patient names, dates of birth, insurance member IDs or treatment details into Slack, email drafts, or the DPCP OS chat. Use the practice's own system and refer to the claim by its internal number only.",
  changes: "When a practice sends you patient details, reply asking them to keep patient details in their own practice system and send only the claim number. The AI will flag messages that look like they contain this.",
  audience: "Company",
  ack: 19,
  question: 2,
  seen: 4,
  unseen: 3,
  total: 28,
};

export function createConnectors(): Connector[] {
  return [
    { id: "workspace", name: "Google Workspace", state: "green", detail: "Account active. 2-step is enforced.", checkedAt: "6:02 AM AZ" },
    { id: "gmail", name: "Gmail intake", state: "green", detail: "Watch is on. Expires Oct 27.", checkedAt: "6:02 AM AZ" },
    { id: "slack-acct", name: "Slack account", state: "green", detail: "Active in the company workspace.", checkedAt: "6:03 AM AZ" },
    { id: "slack-app", name: "DPCP OS Slack app", state: "green", detail: "In the default channels.", checkedAt: "6:03 AM AZ" },
    { id: "td", name: "Time Doctor", state: "red", detail: "No Time Doctor user for jamie.okonkwo@dpcp.example.", checkedAt: "6:04 AM AZ" },
    { id: "role", name: "DPCP OS login and role", state: "green", detail: "Employee · Insurance & Billing · lead Omar Hale.", checkedAt: "6:04 AM AZ" },
    { id: "meet", name: "Meet notes", state: "green", detail: "Drive access check passed.", checkedAt: "6:04 AM AZ" },
    { id: "notice", name: "Work-systems notice", state: "green", detail: "Queued for first login.", checkedAt: "6:05 AM AZ" },
    { id: "backups", name: "Backups", state: "red", detail: "Primary and secondary backup are not both set.", checkedAt: "6:05 AM AZ" },
    { id: "slack-dm", name: "Slack connect on day 1", state: "pending_employee", detail: "Waiting for Jamie. IT's part is done.", checkedAt: "6:05 AM AZ" },
  ];
}

export function createFinishSteps(): FinishStep[] {
  return [
    { id: "ack", title: "Read and acknowledge the work-systems notice", detail: "One tap. Required before your first task.", state: "todo" },
    { id: "slack", title: "Connect Slack", detail: "So your DMs can come into Messages. You do this yourself.", state: "todo" },
    { id: "pwa", title: "Install DPCP OS on your phone", detail: "Add it to your home screen. We check when notifications register.", state: "todo" },
    { id: "td", title: "Time Doctor", detail: "Install the desktop app and sign in with your work email.", state: "todo" },
    { id: "push", title: "Turn on notifications", detail: "Notices, urgent tasks, and approvals that have been waiting.", state: "todo" },
  ];
}

export const ONBOARDING: OnboardingStep[] = [
  { id: "o1", title: "Sign in and set your password", detail: "Google already asked for this.", estimate: "2 min", kind: "read" },
  { id: "o2", title: "Acknowledge the work-systems notice", detail: "Work email and Slack channels are stored by DPCP OS.", estimate: "2 min", kind: "read" },
  { id: "o3", title: "Send a practice reply", detail: "Try it: this practice task is safe. Nothing goes to a client.", estimate: "5 min", kind: "practice" },
  { id: "o4", title: "Sign the confidentiality agreement", detail: "Opens the signature step.", estimate: "5 min", kind: "read" },
  { id: "o5", title: "Meet your lead", detail: "Omar Hale, 15 minutes on Meet.", estimate: "15 min", kind: "read" },
  { id: "o6", title: "Core values", detail: "A short page, then you continue.", estimate: "10 min", kind: "read" },
  { id: "o7", title: "Short quiz", detail: "Three questions. Passing is 2 of 3.", estimate: "5 min", kind: "quiz" },
];

export function createTickets(): Ticket[] {
  return [
    {
      id: "t-existing",
      reporterId: "faisal",
      kind: "idea",
      title: "Show the original due date on the phone card",
      body: "I keep missing that the original date is different from today.",
      impact: "workaround",
      status: "Planned",
      screen: "Today",
      duplicateCount: 3,
    },
  ];
}

export function createMemberships(): Membership[] {
  const rows: Membership[] = PEOPLE.filter((p) => p.departmentId !== "owner").map((p) => ({
    personId: p.id,
    departmentId: p.departmentId,
    teamRole: p.role === "leader" || p.role === "administrator" ? "leader" : "member",
  }));
  rows.push({ personId: "omar", departmentId: "operations", teamRole: "member" });
  return rows;
}

export function createSeed(): Model {
  return {
    tasks: createTasks(),
    messages: createMessages(),
    meetings: createMeetings(),
    decisions: createDecisions(),
    tickets: createTickets(),
    memberships: createMemberships(),
    reviews: createReviews(),
    selectedReviewId: "rev-mesa-email",
    chat: [
      {
        id: "c1",
        kind: "user",
        text: "How many working days do clients get to sign the fee agreement?",
      },
      {
        id: "c2",
        kind: "assistant",
        text: "10 business days from when it's sent. After that the onboarding bot sends a reminder and flags it to your lead.",
        routeNote: "SOP lookup · Client Onboarding SOP v3, section 2 · 4 sec",
      },
      {
        id: "c3",
        kind: "user",
        text: "Get the denial numbers for Saguaro Family Dental and send them to the office manager",
      },
      {
        id: "c4",
        kind: "clarify",
        prompt: "Quick check so I do the right thing:",
        question: "“Denial numbers” could mean a quick count or a full report. Which do you want?",
        options: [
          { id: "count", label: "Just show me this month's denial count here (instant)" },
          { id: "email", label: "Draft an email to the office manager with the numbers (you approve before it sends)" },
          { id: "report", label: "Build the full monthly denial report with reasons and next steps (~25 min, comes back as a task)" },
          { id: "else", label: "Something else…" },
        ],
        routeNote: "Router: not sure which route · asking 1 question instead of guessing",
      },
      {
        id: "c5",
        kind: "job",
        title: "Compare Q3 eligibility rejections across all 6 clients",
        started: "9:58 AM AZ",
        status: "working",
      },
    ],
    clarifyTurns: 0,
    chatContext: null,
    noticeAcked: false,
    noticeQuestioned: false,
    forceNotice: false,
    connectors: createConnectors(),
    finishSteps: createFinishSteps(),
    timeOffStatus: "none",
    onboardingIndex: 2,
    dayClosed: {},
    movedCount: 0,
    blockedCount: 0,
    personPatch: {},
    georgePaused: false,
    selectedDept: "insurance",
    jobDelivered: false,
    checkins: createCheckins(PEOPLE),
    modelRoutes: defaultModelRoutes(),
    rollout: createRollout(PEOPLE),
    georgeInbox: createGeorgeInbox(),
    botChat: [],
    feedback: createFeedback(),
    culture: createCulture(),
    cultureSuggestions: createCultureSuggestions(),
    growthNotes: createGrowthNotes(),
    growthReviews: createGrowthReviews(),
    growthPlans: createGrowthPlans(),
    skills: createSkills(),
    ideas: createIdeas(),
    monday: createMonday(),
    training: createTraining(),
    pulses: createPulses(),
    offboard: createOffboard(),
    cultureIdeas: createCultureIdeas(),
    projects: createProjects(),
    projectTemplates: createProjectTemplates(),
  };
}
